version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db-financas
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Isso garante que seus dados não sumam quando o contêiner for desligado
volumes:
  postgres_data: